### ISSUE TITLE
help request: remap Alt gr

### ISSUE THREAD

**Issue by szaghi** [damko/xkb_kinesis_advantage_dvorak_layout#1]
Dear @damko 

Thank you very much for sharing your work, it is really appreciated.

I need your help: I am using a custom keyboard with a very strange layout, in particular it does not have Alt Gr. I would like to remap it on the right Ctrl. I have tried to play with setxkbmap, but without success.

Can you tell me how to remap the right Ctrl to act as Alt Gr?

I am using US layout.

Thank you very much for any suggestions.

My best regards.

P.S. obviously I am on GNU Linux, Arch Linux to be precise.

**Comment by damko** [comment]
Hello @szaghi 
this should not be too hard. I suppose you are using Alt Gr for diacritics (which are present in Italian) so check this out:

`setxkbmap -model kinesis -layout us,us -variant kinesis_adv_dvorak_it,rus -option "lv3:rwin_switch,grp:alt_space_toggle"`

Let me break it down to pieces:

> -model kinesis 

this is your keyboard model

> -layout: us,us

"us" stands for US layout and you must repeat it as many times as the variants that you are listing right after

> -variant kinesis_adv_dvorak_it,rus

these are the US layout variants that I'm loading. "kinesis_adv_dvorak_it" is a custom layout that I wrote to produce the Italian diacritics (see article linked below) and "rus" is the standard cyrillic alphabet

Now the most interesting part:

> -option "lv3:rwin_switch,grp:alt_space_toggle"

where it says that:

* the right windows key is used as ISO_LEVEL3_SWITCH which is what you need to activate diacritics
* the combination ALT+SPACE will loop among the layout variants (therefore loading US -> Kinesis_adv_dvorak_it -> rus and then start again from US in a loop)

so in your case maybe this is what you need:

`-option "lv3:rctrl_switch,grp:alt_space_toggle"`

BTW I'm not sure if you are aware of [this article](https://medium.com/@damko/a-simple-humble-but-comprehensive-guide-to-xkb-for-linux-6f1ad5e13450) I wrote: it might help you

**Comment by szaghi** [comment]
Hi @damko 

Thank you very much for your kind replay. Indeed, my issue was due to my distraction... I mixed ansi layout with "ansi with variant" (that is what I need...), thus sometimes it worked and some other it did not... For my issue the solution was simple, use always `setxkbmap -layout us -variant altgr-intl` (I forgot the "variant" when it did not worked).

Cheers

**Comment by szaghi** [comment]
Sorry for my fast replay... yes, you are right, without a variant layout the ansi US does not have an "AltGr" to remap.

Thank you very much.

**Comment by damko** [comment]
yes because there are no diacritics in English therefore no need for level 3 (I suppose)
